#!/bin/sh


tell() {
	echo $1
}
prompt() {
	echo $1
	read LASTIN
	
}
Welcome() {
	tell 'My name is wkiam'
	handler='Name'
}

Name() {
	prompt 'What is your name'
	tell "Hello, $LASTIN"
	handler='Exit'
}
Exit() {
	exit
}
handler='Welcome'
while true
do
	eval $handler 
done

